"""add extra_data column to notifications

Revision ID: b42aaeb6fc5d
Revises: 7bc2fbd83ee9
Create Date: 2026-06-20 22:51:26.497512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42aaeb6fc5d'
down_revision: Union[str, Sequence[str], None] = '7bc2fbd83ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'extra_data')
    # ### end Alembic commands ###
